config/routes.rb
Rails.application.routes.draw do
    resources :properties
    resources :tenants
    namespace :tenants do
      devise_scope :tenant do
        get    '/login',  to: 'sessions#new',     as: :new_session
        post   '/login',  to: 'sessions#create',  as: :session
        delete '/logout', to: 'sessions#destroy', as: :destroy_session
      end
    end
  
    devise_for :users, controllers: { registrations: "registrations" }
    get 'admin/index'
  
    resources :units
    root "pages#home"
    get "dashboard", to: "pages#index" ,as: 'dashboard'
    resources :units do
      resources :payments
    end
    resources :tickets
  end
  

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :tenants
  has_many :properties
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/payment.rb
class Payment < ApplicationRecord
    belongs_to :tenant
    belongs_to :unit
  
       def self.payment_types
          ['Credit Card', 'Bank Transfer', 'Cash', 'Cheque']
        end

        # def set_due_date
        #   if self.tenant.present?
        #     start_date = self.tenant.date_of_lease 
        #     end_date = self.tenant.end_date_of_lease
        #     duration = (end_date.year * 12 + end_date.month) - (start_date.year * 12 + start_date.month) + 1
        #     months = (0..duration-1).map { |i| start_date.advance(months: i) }
        #     month_index = self.month - 1
        #     self.due_date = months[month_index].end_of_month
        #   end
        # end
        
end

app/models/property.rb
class Property < ApplicationRecord
  acts_as_tenant(:account)
  has_many :units
  has_many :tenants, through: :units

  def total_rent_collected
    units.sum(:rent)
  end

  def self.for_logged_in_user
    ActsAsTenant.with_tenant(current_user.account) { all }
  end
end

app/models/tenant.rb
class Tenant < ApplicationRecord
 acts_as_tenant(:account)
 has_secure_password
 belongs_to :property
 belongs_to :unit

#  def balance
#     rent_due_date = rent_due || Time.current.to_date
#     payments_total = payments.sum(:amount)
#     rent_total = (end_date_of_lease.year * 12 + end_date_of_lease.month - date_of_lease.year * 12 - date_of_lease.month + 1) * rent_amount
#     rent_due_total = (Time.current.year * 12 + Time.current.month - date_of_lease.year * 12 - date_of_lease.month) * rent_amount
#     rent_due_total -= rent_amount if Time.current.to_date > rent_due_date
#     rent_total - payments_total - rent_due_total
#   end

def full_name
    "#{firstname} #{lastname}"
  end
  def default_rent
    unit.rent
  end

end

app/models/ticket.rb
class Ticket < ApplicationRecord
    acts_as_tenant(:tenant)
end

app/models/unit.rb
class Unit < ApplicationRecord
  
    belongs_to :property, class_name: "Property"
     has_one :tenant
     has_many :payments
    
     
     def assign_tenant(tenant)
        update(status: 'occupied')
       update(tenant_id: tenant.id)
      end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable,
         :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :invitable
  has_one :account

  before_validation :set_account

  def set_account
    self.build_account
  end

  def send_invitation_to(tenant)
    tenant.update(password: SecureRandom.hex(8))
    TenantMailer.invitation(tenant, self, tenant.password).deliver_later
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
 before_action :authenticate_user!,only: [:index]
 before_action :set_current_account,only: [:index]

    def home
        if set_current_account && authenticate_user!
            redirect_to dashboard_path
           end
    end
    def index
        @account = current_user.account
        @units = @account.properties.joins(:units).distinct.select("units.*")
        @units_by_property = Property.joins(:units).group(:name).count
        # @tenants_by_property = Property.joins(units: :tenants).group(:name).count('tenants.id')

    @properties = @account.properties
    end
    
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  def index
    @properties = Property.all
  end
  def new
    @property = Property.new()
  end
  def create
    @property = Property.new(property_params)
    if @property.save
      flash[:success] = "Object successfully created"
      redirect_to @property
    else
      flash[:error] = "Something went wrong"
      render "new"
    end
  end

  def show
    @property = Property.find(params[:id])
    @total_rent_collected = @property.total_rent_collected
    @units = @property.units
    @tenants = []
    @units.each { |unit| @tenants << unit.tenant if unit.tenant }
  end

  private

  def property_params
    params.require(:property).permit(
      :name,
      :location,
      :property_type,
      :category,
      :no_units,
    )
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  def show
    @units = Unit.find(params[:id])
  end
  def index
    @account = current_user.account
    # @units = @account.properties.joins(:units).distinct.select("units.*")
    @units =
      @account
        .properties
        .joins(units: :tenant)
        .distinct
        .select(
          "units.*, tenants.firstname AS tenant_firstname, tenants.lastname AS tenant_lastname",
        )

    @properties = @account.properties
    @payment = Payment.all
  end

  # def index
  #       @properties = Property.all
  #       @units=Unit.all
  # end

  def new
    @unit = Unit.new
    @properties = Property.all
  end

  def create
    @unit = Unit.new(unit_params)
    if @unit.save
      property = @unit.property
      rentals = property.no_units
      property.update(no_units: rentals.to_i + 2)
      redirect_to properties_path
    else
      render "new"
    end
  end

  def search
    property_name = params[:property_name]
    @units =
      Unit.joins(:property).where(
        "properties.name LIKE ?",
        "%#{property_name}%",
      )
  end

  private

  def unit_params
    params.require(:unit).permit(
      :name,
      :bedrooms,
      :bathrooms,
      :rent,
      :property_id,
    )
  end
end

app/controllers/users_controller.rb
class Users::InvitationsController < Devise::InvitationsController
    def update
      if some_condition
        redirect_to root_path
      else
        super
      end
    end
  end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/unit_helper.rb
module UnitHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/properties/edit.html.erb
<h1>Properties#edit</h1>
<p>Find me in app/views/properties/edit.html.erb</p>

app/views/properties/index.html.erb
<%=render "shared/dashnav" %>
    <main class=" pt-3">
        <div class="container-fluid">

            <div class="row ">


                <div class="col-md-12 mb-3  d-flex aligns-items-center justify-content-start  ">
                    <div class="   fw-bolder p-3 text-uppercase ">
                        <%=link_to '<i class="bi-arrow-left-circle text-black  fa-2x  "></i>' .html_safe ,
                            dashboard_url%>
                    </div>


                </div>


            </div>

            <div class="row">
                <div class="col-md-12 mb-3">

                    <div class="card">
                        <div class="card-header d-flex justify-content-between align-content-center text-center">

                            <form class="d-flex" role="search">
                                <input class="form-control me-2" type="search" placeholder="Tamirat Court ...tenants"
                                    aria-label="Search">
                                <button class="btn btn-outline-success" type="submit">Search</button>
                            </form>

                            <%=link_to '<i class="bi bi-plus"></i></span>Create Property'
                                .html_safe,new_property_path,class:""%>

                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table gap-1 " style="width: 100%">
                                    <thead>
                                        <tr
                                            style="font-weight:bold ; text-shadow: 1px 1px #3359df; color: #3359df; font-size: larger; color: #3359df;">
                                            <th> Name</th>
                                            <th>Property Type</th>
                                            <th>No of Units </th>
                                            <th>LandLords</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody style=" text-transform: uppercase; text-shadow: 1px  2px 2px #7cb8e0">


                                        <% @properties.each do |prop|%>
                                            <tr>
                                                <td>
                                                    <%=prop.name%>
                                                </td>
                                                <td>
                                                    <%=prop.category%>

                                                </td>
                                                <td>
                                                    <%=pluralize(prop.units.count,"units")%>
                                                </td>
                                                <td>
                                                    <%=pluralize(prop.units.count,"units")%>

                                                </td>
                                                <td>
                                                    <%=link_to '<i class="bi bi-three-dots-vertical"></i>' .html_safe ,
                                                        property_path(prop)%>
                                                </td>
                                            </tr>
                                            <%end%>




                                    </tbody>

                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

app/views/properties/new.html.erb
<div class="container signup ">
    <div class="vh-100 align-items-center justify-content-center p-5">
        <p class="  align-items-center justify-content-center text-start fw-bolder p-3 text-uppercase ">
            <%=link_to '<i class="bi-arrow-left-circle text-black  text-center fa-2x  "></i>' .html_safe ,
                dashboard_url%>
        </p>
        <div class="row d-flex align-items-center justify-content-center shadow ">
            <div class="col-5 mt-4">
                <div class="card mb-3 border-0">

                    <div class="card-body">
                        <h5 class="card-title" style="color:  rgb(240, 109, 33)">List New Property</h5>
                        <p class="card-text">Create your rental lease using our online lease builder and templates
                            drafted with
                            local law firms, or upload your own lease and e-sign it with your renters</p>

                    </div>
                </div>
            </div>
            <div class="col-md-6 col-sm-12 col-xs-12  p-5 ">
                <h6 class=" text-center fw-bold p-3 text-uppercase" style="color: #3359df;">New Property
                </h6>
                <%=form_with model: @property,data: {turbo: false} do |f|%>
                    <div class="form-group  mb-1">
                        <%= f.label :name %>
                            <%= f.text_field :name, class: 'form-control active' %>
                    </div>
                    <div class=" form-group mb-3">
                        <%=f.label :location,class:"form-label"%>
                            <%=f.text_field :location,class:"form-control"%>
                    </div>
                    <div class="form-group  mb-1">
                        <%= f.label :type %>
                            <%= f.text_field :type, class: 'form-control active' %>
                    </div>
                    <div class=" form-group mb-3">
                        <%=f.label :category,class:"form-label"%>
                            <%=f.text_field :category,class:"form-control"%>
                    </div>


                    <div class="b_submit d-flex justify-content-center align-content-center">
                        <%= f.submit 'New Rentals' .html_safe , class: " mt-2
                            me-3 btn
                            btn-primary" %>
                    </div>
                    <%end%>
            </div>
        </div>
    </div>
</div>

app/views/properties/show.html.erb
<%=render "layouts/nav" %>
    <div class="container-fluid  aligns-items-center justify-content-center">
        <div class="row ">

            <div class="col-md-12  d-flex aligns-items-center justify-content-start  ">

                <div>

                </div>


            </div>

            <div class="col-md-12 fw-bolder text-center  d-flex align-items-center justify-content-between"
                style="color: #3359df;">
                <div class="d-flex align-items-center justify-content-around ">
                    <%= link_to '<i class="bi-arrow-left-circle text-black fa-2x me-3"></i>' .html_safe, properties_url
                        %>
                        <h5 class="mb-0 ml-3">Tenants in <%= @property.name %>
                        </h5>

                </div>
                <h5 class="mb-0 ">House Units
                </h5>
            </div>
        </div>
        <div class="row">
            <div class="col-6 p-2">
                <div class="card">
                    <div class="row">

                        <div class="col-12   align-items-center justify-content-between ">
                            <table class="table ">
                                <thead>
                                    <tr>
                                        <th scope="col">First Name</th>
                                        <th scope="col">Last Name</th>
                                        <th scope="col">Email</th>
                                        <th scope="col">Phone</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <% @tenants.each do |tenant| %>
                                        <tr class="shadow">
                                            <td>
                                                <%= tenant.firstname %>
                                            </td>
                                            <td>
                                                <%= tenant.lastname %>
                                            </td>
                                            <td>
                                                <%= tenant.email %>
                                            </td>
                                            <td>
                                                <%= tenant.phone %>
                                            </td>
                                        </tr>
                                        <% end %>
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
            </div>

            <div class="col-6 p-2">

                <div class="card">
                    <div class="row">

                        <div class="col-12   align-items-center justify-content-between ">
                            <table class="table ">
                                <thead>
                                    <tr>
                                        <th scope="col">name</th>
                                        <th scope="col">Bathrooms</th>
                                        <th scope="col">Bedrooms</th>
                                        <th scope="col">Status</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <% @units.each do |unit| %>
                                        <tr class="shadow">
                                            <td>
                                                <%= unit.name %>
                                            </td>
                                            <td>
                                                <%= unit.bathrooms %>
                                            </td>
                                            <td>
                                                <%= unit.bedrooms %>
                                            </td>
                                            <td>
                                                <%= unit.status %>
                                            </td>
                                        </tr>
                                        <% end %>
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <%= @total_rent_collected%>