config/routes.rb
Rails.application.routes.draw do
    resources :properties
    resources :tenants
    namespace :tenants do
      devise_scope :tenant do
        get    '/login',  to: 'sessions#new',     as: :new_session
        post   '/login',  to: 'sessions#create',  as: :session
        delete '/logout', to: 'sessions#destroy', as: :destroy_session
      end
    end
  
    devise_for :users, controllers: { registrations: "registrations" }
    get 'admin/index'
  
    resources :units
    root "pages#home"
    get "dashboard", to: "pages#index" ,as: 'dashboard'
    resources :units do
      resources :payments
    end
    resources :tickets
  end
  

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :tenants
  has_many :properties
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/payment.rb
class Payment < ApplicationRecord
    belongs_to :tenant
    belongs_to :unit
  
       def self.payment_types
          ['Credit Card', 'Bank Transfer', 'Cash', 'Cheque']
        end

        # def set_due_date
        #   if self.tenant.present?
        #     start_date = self.tenant.date_of_lease 
        #     end_date = self.tenant.end_date_of_lease
        #     duration = (end_date.year * 12 + end_date.month) - (start_date.year * 12 + start_date.month) + 1
        #     months = (0..duration-1).map { |i| start_date.advance(months: i) }
        #     month_index = self.month - 1
        #     self.due_date = months[month_index].end_of_month
        #   end
        # end
        
end

app/models/property.rb
class Property < ApplicationRecord
  acts_as_tenant(:account)
  has_many :units
  has_many :tenants, through: :units

  def total_rent_collected
    units.sum(:rent)
  end

  def self.for_logged_in_user
    ActsAsTenant.with_tenant(current_user.account) { all }
  end
end

app/models/tenant.rb
class Tenant < ApplicationRecord
 acts_as_tenant(:account)
 has_secure_password
 belongs_to :property
 belongs_to :unit

#  def balance
#     rent_due_date = rent_due || Time.current.to_date
#     payments_total = payments.sum(:amount)
#     rent_total = (end_date_of_lease.year * 12 + end_date_of_lease.month - date_of_lease.year * 12 - date_of_lease.month + 1) * rent_amount
#     rent_due_total = (Time.current.year * 12 + Time.current.month - date_of_lease.year * 12 - date_of_lease.month) * rent_amount
#     rent_due_total -= rent_amount if Time.current.to_date > rent_due_date
#     rent_total - payments_total - rent_due_total
#   end

def full_name
    "#{firstname} #{lastname}"
  end
  def default_rent
    unit.rent
  end

end

app/models/ticket.rb
class Ticket < ApplicationRecord
    acts_as_tenant(:tenant)
end

app/models/unit.rb
class Unit < ApplicationRecord
  
    belongs_to :property, class_name: "Property"
     has_one :tenant
     has_many :payments
    
     
     def assign_tenant(tenant)
        update(status: 'occupied')
       update(tenant_id: tenant.id)
      end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable,
         :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :invitable
  has_one :account

  before_validation :set_account

  def set_account
    self.build_account
  end

  def send_invitation_to(tenant)
    tenant.update(password: SecureRandom.hex(8))
    TenantMailer.invitation(tenant, self, tenant.password).deliver_later
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
 before_action :authenticate_user!,only: [:index]
 before_action :set_current_account,only: [:index]

    def home
        if set_current_account && authenticate_user!
            redirect_to dashboard_path
           end
    end
    def index
        @account = current_user.account
        @units = @account.properties.joins(:units).distinct.select("units.*")
        @units_by_property = Property.joins(:units).group(:name).count
        # @tenants_by_property = Property.joins(units: :tenants).group(:name).count('tenants.id')

    @properties = @account.properties
    end
    
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_unit
  def index
    @payments = Payment.where(unit_id: params[:unit_id])
    @unit = Unit.find(params[:unit_id])
  end

  def new
    @unit = Unit.find(params[:unit_id])
    @payment_types = Payment.payment_types
    @payment = @unit.payments.new
    @tenant = @unit.tenant
  end

  def create
    @unit = Unit.find(params[:unit_id])
    @tenant = @unit.id
    @payment = @unit.payments.new(payment_params)

    if @payment.save
      redirect_to unit_path(@unit), notice: "Payment was successfully created."
    else
      render :new
    end
  end

  def edit
    @payment = Payment.find(params[:id])
  end

  def update
    @payment = Payment.find(params[:id])
    if @payment.update(payment_params)
      redirect_to @payment.unit, notice: "Payment was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @payment = Payment.find(params[:id])
    @payment.destroy
    redirect_to @payment.unit, notice: "Payment was successfully deleted."
  end

  private

  def payment_params
    params.require(:payment).permit(
      :amount,
      :date_paid,
      :payment_method,
      :notes,
      :unit_id,
      :tenant_id,
    )
  end
  def set_unit
    @units = Unit.find(params[:unit_id])
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  def show
    @units = Unit.find(params[:id])
  end
  def index
    @account = current_user.account
    # @units = @account.properties.joins(:units).distinct.select("units.*")
    @units =
      @account
        .properties
        .joins(units: :tenant)
        .distinct
        .select(
          "units.*, tenants.firstname AS tenant_firstname, tenants.lastname AS tenant_lastname",
        )

    @properties = @account.properties
    @payment = Payment.all
  end

  # def index
  #       @properties = Property.all
  #       @units=Unit.all
  # end

  def new
    @unit = Unit.new
    @properties = Property.all
  end

  def create
    @unit = Unit.new(unit_params)
    if @unit.save
      property = @unit.property
      rentals = property.no_units
      property.update(no_units: rentals.to_i + 2)
      redirect_to properties_path
    else
      render "new"
    end
  end

  def search
    property_name = params[:property_name]
    @units =
      Unit.joins(:property).where(
        "properties.name LIKE ?",
        "%#{property_name}%",
      )
  end

  private

  def unit_params
    params.require(:unit).permit(
      :name,
      :bedrooms,
      :bathrooms,
      :rent,
      :property_id,
    )
  end
end

app/controllers/users_controller.rb
class Users::InvitationsController < Devise::InvitationsController
    def update
      if some_condition
        redirect_to root_path
      else
        super
      end
    end
  end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/unit_helper.rb
module UnitHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/payments/index.html.erb
<%=render "layouts/nav" %>



    <div class="container=fluid p-3">
        <div class="row">
            <div class="col-md-12">
                <%= link_to " Create Payment" , new_unit_payment_path() %>
                    <h6 class=" text-center">All Payments for <%= @unit.name%> Owner

                    </h6>
                    <div class="pay-table d-flex justify-content-center align-content-center text-center">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Amount</th>
                                    <th>Date</th>
                                    <th>Tenant</th>
                                    <th>Unit</th>
                                    <th>Payment Mode</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                <% @payments.each do |payment| %>

                                    <tr>
                                        <td>
                                            <%= number_to_currency(payment.amount) %>
                                        </td>
                                        <td>
                                            <%=payment.date_paid%>
                                        </td>
                                        <td>
                                            <%= payment.tenant.firstname %>
                                        </td>
                                        <td>
                                            <%= payment.unit.name %>
                                        </td>
                                        <td>
                                            <%= payment.payment_method%>
                                        </td>
                                        <td>
                                            <%= link_to 'Edit Payment' , edit_unit_payment_path(payment.unit,
                                                payment),data: {
                                                confirm: "Are you sure you want to delete this payment?" },
                                                class: 'btn btn-success' %>
                                                <%= link_to "Delete" , unit_payment_path(payment.unit,payment), method:
                                                    :delete, data: {
                                                    confirm: "Are you sure you want to delete this payment?" },
                                                    class: 'btn btn-danger' %>
                                        </td>
                                    </tr>
                                    <% end %>
                            </tbody>
                        </table>
                    </div>
            </div>

        </div>
    </div>

app/views/payments/new.html.erb
<%=render "layouts/nav" %>
    <div class="container">
        <div class="row">


            <div class="col-12">
                <h6 class="text-center">New Payment for [ <%=@unit.name%>]</h6>

                <%= form_with(model: [@unit, @payment], url: unit_payments_path(@units)) do |f| %>
                    <div class="form-control m-3">
                        <%= f.label :amount %>
                            <%= f.number_field :amount, class: 'form-control' %>
                    </div>

                    <div class="form-control m-3">
                        <%= f.label :date %>
                            <%= f.date_field :date, class: 'form-control' %>
                    </div>

                    <div class="form-control m-3 d-none">
                        <%= f.label :tenant_id, "Tenant" %>
                            <%= f.collection_select(:tenant_id, Tenant.all, :id, :full_name, {selected:
                                @unit.tenant.id}, {class: 'form-control hidde' }) %>
                    </div>

                    <div class="form-control m-3">
                        <%= f.label :tenant_id, "Tenant" %>
                            <%= f.collection_select(:tenant_id, Tenant.where(id: @unit.tenant_id), :id, :full_name, { },
                                { class: "form-control" , disabled: true }) %>

                    </div>

                    <div class="form-control m-3">

                        <%= f.collection_select(:payment_type, @payment_types, :to_s, :to_s,
                            {prompt: "Select a payment type" }, {class: 'form-control' }) %>

                    </div>
                    <div class="form-control m-3">
                        <%= f.label :note %>
                            <%= f.text_area :note, class: 'form-control' %>
                    </div>

                    <div class="d-flex justify-content-center align-items-center">
                        <%= f.submit "Make Payment" , class: 'btn btn-primary' %>
                    </div>
                    <% end %>
            </div>
        </div>
    </div>

app/views/payments/show.html.erb
<!-- app/views/payments/show.html.erb -->

<h6>Payment Details <%= @payments %>
</h6>
<p class="  align-items-center justify-content-center text-start fw-bolder  text-uppercase ">
    <%=link_to '<i class="bi-arrow-left-circle text-black  text-center fa-2x  "></i>' .html_safe , dashboard_url%>
</p>
<table class="table">
    <tr>
        <th>Amount</th>
        <td>
            <%= number_to_currency(@payments.amount) %>
        </td>
    </tr>
    <tr>
        <th>Date</th>
        <td>
            <%= @payments.date.strftime("%B %e, %Y") %>
        </td>
    </tr>
    <tr>
        <th>Tenant</th>
        <td>
            <%= @payments.tenant.name %>
        </td>
    </tr>
    <tr>
        <th>Unit</th>
        <td>
            <%= @payments.unit.number %>
        </td>
    </tr>
    <tr>
        <th>Note</th>
        <td>
            <%= @payments.note %>
        </td>
    </tr>
</table>

<%= link_to "Edit Payment" , edit_payment_path(@payment.unit,@paymen), class: 'btn btn-primary' %>
    <%= link_to "Back to Payments" , payments_path, class: 'btn btn-secondary' %>